sqlite: &sqlite
  adapter:  sqlite3
  pool:     5
  timeout:  5000

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: yaprom
  database: yaprom

test:
  <<: *sqlite
  database: db/test.sqlite3

development:
  <<: *sqlite
  database: db/development.sqlite3

production:
  <<: *sqlite
  database: db/production.sqlite3
