postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: yaprom
  username: yaprom
  pool: 5

test:
  adapter:  sqlite3
  database: db/test.sqlite3
  pool:     5
  timeout:  5000

development:
  <<: *postgresql
  password: yaprom

production:
  <<: *postgresql
  password: ducVeumjiBliwacObgiHennEtKetjic2
